# source: https://github.com/BamPeers/rust-ci-github-actions-workflow

on:
  pull_request:
  push:
    branches:
      - master

name: Test with Code Coverage

env:
  GUROBI_DOWNLOAD: https://packages.gurobi.com/9.5/gurobi9.5.1_linux64.tar.gz
  GUROBI_DEST: /opt
  GUROBI_HOME: /opt/gurobi951/linux64
  LD_LIBRARY_PATH: /opt/gurobi951/linux64/lib

defaults:
  run:
    working-directory: ./dp-planner

jobs:
  test:
    name: Test
    env:
      PROJECT_NAME_UNDERSCORE: rust_ci_github_actions_workflow
      CARGO_INCREMENTAL: 0
      RUSTFLAGS: -Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort
      RUSTDOCFLAGS: -Cpanic=abort
    defaults:
      run:
        working-directory: ./dp-planner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites for https://crates.io/crates/gmp-mpfr-sys
        run: sudo apt-get install -y diffutils gcc m4 make
      - name: Download and Unarchive Gurobi
        run: curl -o ~/gurobi.tar.gz $GUROBI_DOWNLOAD && tar -xvf ~/gurobi.tar.gz -C $GUROBI_DEST
      - uses: actions-rs/toolchain@v1
        with:
          #profile: minimal
          toolchain: nightly
          override: true
#      - name: Cache dependencies
#        uses: actions/cache@v2
#        env:
#          cache-name: cache-dependencies
#        with:
#          path: |
#            ~/.cargo/.crates.toml
#            ~/.cargo/.crates2.json
#            ~/.cargo/bin
#            ~/.cargo/registry/index
#            ~/.cargo/registry/cache
#            target
#          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('Cargo.lock') }}

      - uses: actions-rs/cargo@v1
        with:
          command: test
          use-cross: false
          args:  --all-features --no-fail-fast -- --skip "::ilp::"
        #--manifest-path dp-planner/Cargo.toml
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
          RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
      - id: coverage
        uses: actions-rs/grcov@v0.1

      - name: Coveralls upload
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ steps.coverage.outputs.report }}
